displayName: Timeout Plugin
type: middleware

import: github.com/Kichiyaki/traefiktimeout

summary: 'https://pkg.go.dev/net/http#TimeoutHandler for Traefik'

testData:
  timeout: '1s'
  message: 'Timeout'
